// Code generated by mockery v2.43.2. DO NOT EDIT.

package repository

import (
	context "context"
	core "myapp/domain/core"

	mock "github.com/stretchr/testify/mock"
)

// BankInfoRepository is an autogenerated mock type for the BankInfoRepository type
type BankInfoRepository struct {
	mock.Mock
}

// CreateBank provides a mock function with given fields: ctx, bank
func (_m *BankInfoRepository) CreateBank(ctx context.Context, bank *core.Bank) (uint, error) {
	ret := _m.Called(ctx, bank)

	if len(ret) == 0 {
		panic("no return value specified for CreateBank")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.Bank) (uint, error)); ok {
		return rf(ctx, bank)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *core.Bank) uint); ok {
		r0 = rf(ctx, bank)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *core.Bank) error); ok {
		r1 = rf(ctx, bank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBankInfoRepository creates a new instance of BankInfoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBankInfoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BankInfoRepository {
	mock := &BankInfoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
