// Code generated by mockery v2.43.2. DO NOT EDIT.

package contract

import (
	context "context"
	command "myapp/app/operation/command"

	mock "github.com/stretchr/testify/mock"

	operation "myapp/app/operation"
)

// AddBankCommandHandler is an autogenerated mock type for the AddBankCommandHandler type
type AddBankCommandHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *AddBankCommandHandler) Handle(_a0 context.Context, _a1 command.AddBankCommand) (operation.AddBankResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 operation.AddBankResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, command.AddBankCommand) (operation.AddBankResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, command.AddBankCommand) operation.AddBankResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(operation.AddBankResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, command.AddBankCommand) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAddBankCommandHandler creates a new instance of AddBankCommandHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddBankCommandHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddBankCommandHandler {
	mock := &AddBankCommandHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
