// Code generated by mockery v2.43.2. DO NOT EDIT.

package contract

import (
	context "context"
	operation "myapp/app/operation"

	mock "github.com/stretchr/testify/mock"

	query "myapp/app/operation/query"
)

// GetBankQueryHandler is an autogenerated mock type for the GetBankQueryHandler type
type GetBankQueryHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, _a1
func (_m *GetBankQueryHandler) Handle(ctx context.Context, _a1 query.GetBankQuery) (operation.BankResponse, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 operation.BankResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.GetBankQuery) (operation.BankResponse, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.GetBankQuery) operation.BankResponse); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(operation.BankResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.GetBankQuery) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetBankQueryHandler creates a new instance of GetBankQueryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetBankQueryHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetBankQueryHandler {
	mock := &GetBankQueryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
