// Code generated by mockery v2.43.2. DO NOT EDIT.

package contract

import (
	context "context"
	operation "myapp/app/operation"

	mock "github.com/stretchr/testify/mock"

	query "myapp/app/operation/query"
)

// GetPaymentQueryHandler is an autogenerated mock type for the GetPaymentQueryHandler type
type GetPaymentQueryHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, _a1
func (_m *GetPaymentQueryHandler) Handle(ctx context.Context, _a1 query.GetPaymentQuery) (operation.PaymentResponse, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 operation.PaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.GetPaymentQuery) (operation.PaymentResponse, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.GetPaymentQuery) operation.PaymentResponse); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(operation.PaymentResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.GetPaymentQuery) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetPaymentQueryHandler creates a new instance of GetPaymentQueryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetPaymentQueryHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetPaymentQueryHandler {
	mock := &GetPaymentQueryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
