// Code generated by mockery v2.43.2. DO NOT EDIT.

package contract

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BankServiceProvider is an autogenerated mock type for the BankServiceProvider type
type BankServiceProvider struct {
	mock.Mock
}

// CheckBankDetails provides a mock function with given fields: ctx, accountNumber, ifscCode
func (_m *BankServiceProvider) CheckBankDetails(ctx context.Context, accountNumber int64, ifscCode string) (bool, error) {
	ret := _m.Called(ctx, accountNumber, ifscCode)

	if len(ret) == 0 {
		panic("no return value specified for CheckBankDetails")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (bool, error)); ok {
		return rf(ctx, accountNumber, ifscCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = rf(ctx, accountNumber, ifscCode)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, accountNumber, ifscCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBankServiceProvider creates a new instance of BankServiceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBankServiceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *BankServiceProvider {
	mock := &BankServiceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
